</body>

<!--MOCHAUI-->
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Core/core.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Core/create.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Core/require.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Core/canvas.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Core/content.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Core/persist.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Core/themes.js"></script>

<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/accordion/accordion.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/checkboxgrid/checkboxgrid.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/column/column.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/desktop/desktop.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/dock/dock.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/dockhtml/dockhtml.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/form/form.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/imagebutton/imagebutton.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/list/list.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/menu/menu.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/pager/pager.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/panel/panel.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/selectlist/selectlist.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/spinner/spinner.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/stepper/stepper.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/tabs/tabs.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/taskbar/taskbar.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/textarea/textarea.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/textbox/textbox.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/themechange/themechange.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/toolbar/toolbar.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/tree/tree.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>vendor/main/Controls/window/window.js"></script>

<?php if (Obj()->Vendor->Session->get('sys_isLogin')) : ?>
<script type="text/javascript" src="<?php echo BASE_URL; ?>app/system/views/init/js/Init.js"></script>
<?php endif; ?>


<script>
    /*obtener el src de los js incluidos, para verificar que no sean suplantados*/
    /*
     $.each($('script'),function(){
     alert($(this).attr('src'))
     });
     */
    Exe.require("<?php echo BASE_URL; ?>vendor/main/Tools");
    Exe.require("<?php echo BASE_URL; ?>config/lang/js/lang_<?php echo APP_LANG?>");
    Exe.require("<?php echo BASE_URL; ?>libs/Aes/js/aes",function(){
        Exe.require("<?php echo BASE_URL; ?>libs/Aes/js/aesctr");
    });    
    Exe.require("<?php echo BASE_URL; ?>libs/Aes/js/base64");
    Exe.require("<?php echo BASE_URL; ?>libs/Aes/js/utf8");
    
</script>
</html>