<!DOCTYPE html>
<html lang="en" dir="ltr" itemscope itemtype="http://schema.org/Article">
<head>
    <meta charset="utf-8">
	
	<title>Livian Framework</title>
	<meta name="description"
		  content="A web applications user interface library built on the Mootools JavaScript framework"/>

	<!--<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>Source/Themes/default/css/window.css"/>-->
<!--	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>Source/Themes/default/css/desktop.css"/>
	<link rel="stylesheet" type="text/css" href="<?php echo $rutaLayout['css']; ?>Themes/default/css/demo.css"/>-->
	
	<script type="text/javascript" src="<?php echo $rutaLayout['js']; ?>mootools-core-1.5.0-full-nocompat.js"></script>
	<script type="text/javascript" src="<?php echo $rutaLayout['js']; ?>mootools-more-1.5.0.js"></script>

	
</head>
<body>