<!DOCTYPE html>
<html lang="en" dir="ltr" itemscope itemtype="http://schema.org/Article">
<head>
    <meta charset="utf-8">
	<title>Livian Framework</title>
	<meta name="description" content="Livian Framework"/>
	<script type="text/javascript" src="<?php echo $rutaLayout['js']; ?>mootools-core-1.5.0-full-nocompat.js"></script>
	<script type="text/javascript" src="<?php echo $rutaLayout['js']; ?>mootools-more-1.5.0.js"></script>
</head>
<body>