<!DOCTYPE html>
<html lang="en" dir="ltr" itemscope itemtype="http://schema.org/Article">
<head>
    <meta charset="utf-8">
	
	<title>Livian Framework</title>
	<meta name="description"
		  content="A web applications user interface library built on the Mootools JavaScript framework"/>

	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>Source/Themes/default/css/window.css"/>
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>Source/Themes/default/css/desktop.css"/>
	<link rel="stylesheet" type="text/css" href="<?php echo $rutaLayout['css']; ?>Themes/default/css/demo.css"/>
	
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Demo/scripts/mootools-core-1.5.0-full-nocompat.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Demo/scripts/mootools-more-1.5.0.js"></script>

	<!--MOCHAUI-->
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Source/Core/core.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Source/Core/create.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Source/Core/require.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Source/Core/canvas.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Source/Core/content.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Source/Core/persist.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Source/Core/themes.js"></script>

	<script type="text/javascript" src="<?php echo BASE_URL; ?>Source/Controls/window/window.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL; ?>Source/Controls/desktop/desktop.js"></script>
</head>
<body>