
<div id="desktop">
</div>

<script>
    new MUI.Window({
			id: 'ajaxpage',
			content: [
				{url: '{demo}pages/lipsum.html'},
				{position:'header',control:'MUI.Toolbar',buttons:[{cssClass: 'icon_application_go', title: 'Go'}]},
				{position:'footer',control:'MUI.Toolbar',buttons:[{cssClass: 'icon_application_go', title: 'Go'}]}
			],
			width: 340,
			height: 150,
			draggable: true
		});
</script>