<style>
    body{
        margin: 0px;
        background: #F2F2F2 url(public/img/abstracto-azul-fondos.jpg) no-repeat;
        font-family: arial;
    }
    .panel_login{
        width: 600px;
        margin: auto;
        margin-top: 10%;
        padding: 60px 30px 30px 30px;
        position: relative;
        background: #2F4B68;
        -webkit-box-shadow: -1px 2px 18px 8px rgba(0,0,0,0.75);
        -moz-box-shadow: -1px 2px 18px 8px rgba(0,0,0,0.75);
        box-shadow: -1px 2px 18px 8px rgba(0,0,0,0.75);
    }
    .img_login, .form_login, .panel_login{
        border-radius: 5px 5px 5px 5px;
        -moz-border-radius: 5px 5px 5px 5px;
        -webkit-border-radius: 5px 5px 5px 5px;
        height: 300px;
    }
    .img_login{
        background: #718BA6;
        width: 25%;
        float: left;
    }
    .form_login{
        background: #F2F2F2;
        width: 73%;
        float: right;
    }
    .title_login{
        position: absolute;
        top:15px;
        color: #fff;
        font-weight: bold;
    }
    .img_login img{
        margin-left: 15px;
        margin-top: 60px;
    }
</style>


<div class="panel_login">
    <div class="title_login">ACCESO AL SISTEMA</div>
    <div class="img_login">
        <img src="public/img/l1.png">
    </div>
    <div class="form_login"></div>
</div>

