<style>
    body{
        margin: 0px;
        background: #F2F2F2 url(public/img/abstracto-azul-fondos.jpg) no-repeat;
        font-family: arial;
    }
    a{
        text-decoration: none;
    }
    .panel_login{
        width: 600px;
        margin: auto;
        margin-top: 10%;
        padding: 60px 30px 30px 30px;
        position: relative;
        background: #2F4B68;
        -webkit-box-shadow: -1px 2px 18px 8px rgba(0,0,0,0.75);
        -moz-box-shadow: -1px 2px 18px 8px rgba(0,0,0,0.75);
        box-shadow: -1px 2px 18px 8px rgba(0,0,0,0.75);
        opacity: 0.9;
    }
    .img_login, .form_login, .panel_login{
        border-radius: 5px 5px 5px 5px;
        -moz-border-radius: 5px 5px 5px 5px;
        -webkit-border-radius: 5px 5px 5px 5px;
        height: 300px;
    }
    .img_login{
        background: #718BA6;
        width: 25%;
        float: left;
    }
    .form_login{
        background: #F2F2F2;
        width: 73%;
        float: right;
    }
    .title_login{
        position: absolute;
        top:15px;
        color: #fff;
        font-weight: bold;
    }
    .img_login img{
        margin-left: 15px;
        margin-top: 60px;
    }
    .form_login button{
        height: 24px;
        margin: 0;
        padding: 3px 6px;
        background: #f1f1f1;
        font-size: 12px;
        font-weight: bold;
        cursor: pointer;
        vertical-align: middle;
        border: 1px solid #808080;
        border-radius: 3px;
        -moz-border-radius: 3px;
        -webkit-border-radius: 3px;
    }
    .form_login table{
        margin: auto;
        margin-top: 40px;
    }
    .form_login input{
        width: 100%;
        padding: 2px;
    }
    .center{
        text-align: center;
    }
    .copy{
        color: #fff;
        margin: auto;
        margin-top: 30px;
    }
</style>


<div class="panel_login">
    <div class="title_login">ACCESO AL SISTEMA</div>
    <div class="img_login">
        <img src="public/img/l1.png">
    </div>
    <div class="form_login">
        <table width="70%" border="0" cellpadding="5">
            <tbody>
                <tr>
                    <td>Usuario</td>
                </tr>
                <tr>
                    <td>
                        <input type="text" id="txtUser" name="txtUser">
                    </td>
                </tr>
                <tr>
                    <td>Contraseña</td>
                </tr>
                <tr>
                    <td>
                        <input type="text" id="txtClave" name="txtClave">
                    </td>
                </tr>
                <tr>
                    <td class="center">
                        <button type="button" id="btnEntrar">Entrar</button>
                    </td>
                </tr>
                <tr>
                    <td>
                        <br><a href="javascript:;">Olvide mi contraseña</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="copy center"> &copy; 2017 Perú - Todos los derechos reservados</div>

<script>
    $(function () {
        Exe.require({system: 'Login'});
    });
</script>